apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password1
  MYSQL_DATABASE: mydb
  MYSQL_USER: demo_user
  MYSQL_PASSWORD: Demo@123
