apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: my-app
spec:
  ingressClassName: nginx
  rules:
  - host: myfullstackproject.local
    http:
      paths:
      - path: /customers
        pathType: Prefix
        backend:
          service:
            name: backendsvc
            port:
              number: 8080

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontsvc
            port:
              number: 80
